### PR TITLE
[RFR] Optimize build process

### PR DESCRIPTION
**Pull request by jpetitcolas**
Add better uglification, optimize Webpack internal ids and remove eventually duplicated code.

Before:

``` sh
$ ls -lh build/
total 2,8M
-rw-r--r-- 1 jpetitcolas jpetitcolas 1,4M May 29 10:01 ng-admin.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 814K May 29 10:01 ng-admin.min.js
-rw-r--r-- 1 jpetitcolas jpetitcolas 7,0K May 29 10:01 ng-admin-only.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 593K May 29 10:01 ng-admin-only.min.js
```

After:
``` sh
$ ls -lh build/
total 2,7M
-rw-r--r-- 1 jpetitcolas jpetitcolas 1,4M May 29 10:02 ng-admin.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 796K May 29 10:02 ng-admin.min.js
-rw-r--r-- 1 jpetitcolas jpetitcolas 7,0K May 29 10:02 ng-admin-only.min.css
-rw-r--r-- 1 jpetitcolas jpetitcolas 575K May 29 10:02 ng-admin-only.min.js
```

### CODE REVIEW

**Comment by manuquentin** [comment]
Thanks for polar bears !

**Comment by jpetitcolas** [comment]
image

**Comment by jeromemacias** [comment]
Please do not commit built files to avoid conflict.

**Comment by jeromemacias** [comment]
Can you rebase ?

**Pull request merged**
