### PR TITLE
WYSIWYG field sanitization enableable

### PR DESCRIPTION
**Pull request by ihrigb**
WYSIWYG field sanitization can be enabled or disabled by field configuration.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks!

**Comment by ihrigb** [comment]
You're welcome!
Thank you for providing ng-admin! It really made my life easier!

**Comment by ihrigb** [comment]
Btw. when you expect the next release including this merge to have it available via bower?

**Comment by fzaninotto** [comment]
The minified files have already been rebuilt, it's available on master. As for the next release, it's not planned yet, but I'd say in less than a month.

**Pull request merged**
