### PR TITLE
[RFR] Fix error messages on failed deletes, updates

### PR DESCRIPTION
**Pull request by jpetitcolas**

### CODE REVIEW

**Comment by jpetitcolas** [comment]
Closes #1129 and #1130.

**Comment by RichardBradley** [comment]
(It doesn't close all of #1129, just makes it better. See comments on #1130)

**Comment by Phocea** [comment]
@jpetitcolas do you have an ETA on this merge by any chance ?

**Comment by jpetitcolas** [comment]
@Phocea: a few seconds ago. :)

**Comment by Phocea** [comment]
works a treat, much better.
Do you think this one could also be merged https://github.com/marmelab/ng-admin/pull/1223 so we also get the error message displayed correctly when happening on state change?

Will open another PR later with a way to configure the redirect depending on  the http code error

**Pull request merged**
