### PR TITLE
[RFR] Allow ListView filters on references

### PR DESCRIPTION
**Pull request by jeromemacias**
image

* [x] Make filter on references works
* [x] Add tests

### CODE REVIEW

**Comment by jeromemacias** [comment]
Needs some refactoring, I should not use any View for filters.

**Comment by fzaninotto** [comment]
Could you fix the remaining test?

**Comment by fzaninotto** [comment]
Also, can you explore a way to reduce the list width? The filter layout isn't that great in the screenshot.

**Comment by jeromemacias** [comment]
@fzaninotto done

**Comment by F3L1X79** [comment]
I'm sorry to ask this, but could you give a sample of code to Filter by Reference Field?
In the doc, it's written: "Filter fields can be of any type, including reference and template. This allows to define custom filters with ease."
But when I try to add a custom Reference filter on my ListView:
‘‘‘js
]).filters([
                nga.field('clientId', 'reference')
                    .label('Utilisateur associé')
                    .targetEntity(client)
                    .targetField(nga.field('email'))
            ])
‘‘‘
I got a "State Change Error : Entry is not defined".
I'd like to get some help on this, please.

**Comment by F3L1X79** [comment]
Ok I've found a solution:
I need to add 
.remoteComplete(true, {
                        refreshDelay: 200,
                        searchQuery: function(search) { return { q: search }; }
                    })
like in the demo!

**Pull request merged**
