### PR TITLE
#1157 add an issue template with a request for Plunkr repro steps

### PR DESCRIPTION
**Pull request by RichardBradley**
First draft of an issue template re #1157

### CODE REVIEW

**Comment by fzaninotto** [comment]
Awesome, thanks!

**Comment by Phocea** [comment]
@RichardBradley your template does not seems to work anymore with latest master code :(

**Comment by RichardBradley** [comment]
Yes, the published built files were removed recently at https://github.com/marmelab/ng-admin/commit/4d586e6e79a69e9db2444ec8d96506e807369335

I'm not sure what the Plunkr demo should use instead? Are they now published on npm or similar? 
Maybe http://marmelab.com/ng-admin-demo/build/ng-admin.min.js ?

**Comment by Phocea** [comment]
Not sure myself. The updated documentation still refer to the build file. using webpack I actually built it myself.
The problem with the ng-admin-demo is that we can never be sure of it's version. At the moment it is not pointing to the master code or the latest published version (<div ui-view> has not been updated with necessary changes)
@jpetitcolas are those files still planned to be built and published on this repo?

**Comment by jpetitcolas** [comment]
@Phocea: no, built files won't be committed on this repository anymore. However, we can use unpkg to get final files: https://unpkg.com/ng-admin/build/ng-admin.min.js (as they are built during npm publishing). We need to update the PlunkR and to indicate it points to last published version.

**Comment by Phocea** [comment]
@jpetitcolas great. This is indeed working U(http://plnkr.co/edit/JkgrLFgvz7jP6Ee6w0m9). I dont have write access to the original plunkr though. @RichardBradley can you make the update please ?

**Comment by RichardBradley** [comment]
I tried, but I don't have write permissions to the "qrw9Y8rfUUmHM4rOJo1q" plunkr either, it belongs to http://plnkr.co/users/sam2x https://github.com/sam2x

It might be better to update the issue template to point to a plunkr under the control of a regular contributor?

**Pull request merged**
