### PR TITLE
[RFR] Update README for Webpack

### PR DESCRIPTION
**Pull request by jpetitcolas**

### CODE REVIEW

**Comment by manuquentin** [comment]
Tests fails :stuck_out_tongue_closed_eyes:

**Comment by fzaninotto** [comment]
If I understand correctly, "standalone" contains all dependencies and "" contains only the ng-admin code. It's kind of backwards, and breaks BC badly...

**Comment by jpetitcolas** [comment]
True for BC. Let's switch to `ng-admin-only` and `ng-admin` in this case.

**Comment by fzaninotto** [comment]
or `ng-admin-no-deps` to make it obvious.

**Comment by fzaninotto** [comment]
wait, it's not obvious. Let's keep `only`.

**Pull request merged**
