### PR TITLE
[RFR] Make custom elements translatable

### PR DESCRIPTION
**Pull request by djhi**
Entities labels, fields labels, menus labels, choices values are now translatable.
all_the_things

### CODE REVIEW

**Comment by jpetitcolas** [comment]
Can you update the doc to give an example on how to translate fields?

**Comment by djhi** [comment]
I'm working on it

**Comment by djhi** [comment]
documentation updated

**Comment by fzaninotto** [comment]
All good, thanks a lot!

**Comment by djhi** [comment]
My pleasure, can we have an alpha 3 soon ?

**Pull request merged**
