### PR TITLE
[RFR] Fix Karma tests

### PR DESCRIPTION
**Pull request by jpetitcolas**
In WIP. Trying to identify the issue first.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Any progress?

**Comment by jpetitcolas** [comment]
Not yet. Can't find the issue. I'll look at it more deeply later today.

**Comment by jpetitcolas** [comment]
Succeeded to reproduce, using PhantomJS instead of Chrome with command line:

``` sh
CI=true grunt test
```

Looking at a fix.

**Comment by jpetitcolas** [comment]
Switching to RFR. Tests should finally be green (modulo the current GitHub DDOS attack).

**Comment by fzaninotto** [comment]
\o/

**Pull request merged**
