### PR TITLE
[FIX] wording typo (Typo in Documentation #1078)

### PR DESCRIPTION
**Pull request by bestori**
Good catch, cfatt10 :)

### CODE REVIEW

**Comment by bestori** [comment]
CI fails have nothing to do with commit..

**Comment by cfatt10** [comment]
Thanks for making the pull request! It looks like you actually found another spot where 'literal' was misspelled. The original sentence was 

> When given an array, each choice must be an object litteral with both a value and a label.
And the sentence you found is

> Symmetrically, passing an object litteral as argument to the setter methor `view.fields(fields)` is deprecated ;
See issue #1078 for location of first sentence

**Comment by bestori** [comment]
Hehe ok, fixing that one as well :) Any idea why checks are failing?? it appears as though it's the status of the current version...?

**Comment by fzaninotto** [comment]
Thanks! I don't understand why tests fail on travis, it's unrelated to your change.

**Comment by bestori** [comment]
Thanks! 👍  :)

**Pull request merged**
