### PR TITLE
Update API-mapping.md

### PR DESCRIPTION
**Pull request by narigua**
Just a little update on doc for API that respond with a 206 partial or 200, check for JSON lengh.

### CODE REVIEW

**Comment by endel** [comment]
I don't agree with this. The previous example was just enough to describe how to integrate with your back-end.

**Comment by fzaninotto** [comment]
So that means your API doesn't include the Content-Range header when there is no pagination? I'm not sure that's standards compliant, in which case I agree with @endel.

**Comment by narigua** [comment]
It's a Symfony2 project RESTFUL API, with Symfony best practice, it's not my only mind.

In this example, with a content-range, it's not useful add to header too much information when you have a little response. But it's a choice ;)

**Comment by fzaninotto** [comment]
I don't see any `Content-Range` header in FOSRestBundle, which bundle are you using?

**Comment by narigua** [comment]
http://jmsyst.com/bundles/JMSSerializerBundle

**Comment by fzaninotto** [comment]
I don't see any `Content-Range` header there either...

**Comment by narigua** [comment]
I'll give you this tomorrow, when i'm on the project.

**Comment by fzaninotto** [comment]
Any updates on this one? As I don't see where the `Content-Range` header is set "the standard way" in your library, I'm tempted to close your PR.

**Pull request closed without merging**
