### PR TITLE
[WIP] Fix tests due to Angular 1.4 version switch

### PR DESCRIPTION
**Pull request by jpetitcolas**
Still WIP as I'd like to ensure nothing is broken manually first.

For more details about this change: https://docs.angularjs.org/guide/migration#ngoptions

### CODE REVIEW

**Comment by jeromemacias** [comment]
Test e2e failed.

**Comment by fzaninotto** [comment]
Can't we support both 1.3 and 1.4?

**Comment by jeromemacias** [comment]
We maybe need to provide 2 separate packages for the full ng-admin (the one ith AngularJs included).

Something like `ng-1.4-admin.min.js` and `ng-admin.js`.
It could be possible to have an `ng-admin-only.js`with an angular 1.3 and 1.4 compatibility.

**Comment by jpetitcolas** [comment]
Not a big fan of having to maintain several versions. It would be better to continue supporting 1.3 while it is stable. When 1.4 will be stable, then deliver a new release using the new version.

**Comment by fzaninotto** [comment]
1.4 is stable. We should identify the parts in the codebase that break on 1.4.

**Comment by jpetitcolas** [comment]
Soon superseeded by #567.

**Pull request closed without merging**
