### PR TITLE
[RFR] Strip tags in list wysiwyg fields

### PR DESCRIPTION
**Pull request by jpetitcolas**
Refs #129.

- [x] Strip tags when displaying WYSIWYG fields in List/Dashboard views
- [x] Unit test filter

### CODE REVIEW

**Comment by jpetitcolas** [comment]
I'm wondering if we shouldn't add a line break (or at least a space) when we deal with block tags? Indeed, in the first record, `Title` is glued to the next paragraph. Any opinion?

image

We can't replace tags by a simple `space`, otherwise we would get too much space in some cases such as:

``` A short <strong>phrase</strong>.``` => ``` A short phrase .```

**Comment by fzaninotto** [comment]
Valid concern, but let's not be too smart for now. I guess PHP's `strip_tags()` has the same shortcomings, we can live with it for the time being.

**Comment by fzaninotto** [comment]
It's not necessary to commit built files. It makes merging harder, and we regularly rebuild on master.

**Comment by jpetitcolas** [comment]
Added unit tests and switching to RFR. I reverted the changes brought to `build/*` files.

**Comment by fzaninotto** [comment]
Needs rebase

**Comment by jpetitcolas** [comment]
Rebased

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
