### PR TITLE
Fix date field write widget

### PR DESCRIPTION
**Pull request by manuelnaranjo**
Date field write widget was inside a wrong container, making it display ugly

### CODE REVIEW

**Comment by fzaninotto** [comment]
What? No, limiting the date widget width was done on purpose, and it works fine. See the example from the demo:

image

Can you show us the visual difference between before and after your PR?

**Comment by manuelnaranjo** [comment]
I had an example, if I reproduce it again I post it here, want to close this until then?

I've been thinking that row, label and field classes should be configurable, I've been thinking on how to implement this, when I make a demo I open an issue.

**Comment by manuelnaranjo** [comment]
Found it!

ng-admin-dates

I can give you guys access to our server so you can look at it by your selfs if anyone is willing to look at it. Just look for me at gitter.

**Comment by fzaninotto** [comment]
Did you customize the CSS?

**Comment by manuelnaranjo** [comment]
@fzaninotto nope, the date field is set to col-sm-4 by default which is too short for displaying this dates.

**Comment by fzaninotto** [comment]
Superseded by #673

**Pull request closed without merging**
