### PR TITLE
Added missing EditView.getUrl parameter

### PR DESCRIPTION
**Pull request by SebLours**
Patch for #871 (EditView, not ListView)

### CODE REVIEW

**Comment by fzaninotto** [comment]
Could you remove the built files from your PR? They make it hard to merge. I'll rebuild the files myself once merged.

**Comment by SebLours** [comment]
:rewind:  It's done

**Comment by SebLours** [comment]
I ask my self if this PR is ready ...

For example a route like this (entity with a composite keys id): /#/crew_members/edit/2501,1947
The id will be passed as string (`'2501,1947'`) at EditView.getUrl, i think the `id` argument must be an array `[2501,1947]`

I don't know how to get the id as array from $state.params ...

**Comment by fzaninotto** [comment]
Thanks!

**Pull request merged**
