### PR TITLE
[RFR] Delete button state-params fix

### LINKED ISSUE #535: Delete button directive-params are overriden by state-params
[Here you can see](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/button/maDeleteButton.js#L19) that directive params (`entity` and `id`) are always overriden with state params (`entry` and `id` from object which is returned from `$state.params` call).
In practice it causes wrong behaviour whenever we try to place `Delete` button in other entity's view. For example I have `Post` which may have many `Images` and use `referenced_list` field type to view list of related `Images`  in `Post`'s edit view. If i place `<ma-delete-button entry="::entry" entity="::entity()" size="xs"></ma-delete-button>` directive to the `refernced_list` table (as `template` field type), delete button will direct user to the `Post` deletion view, not `Image` deletion view. This is a bug, and I've made a fix for it: vasiakorobkin/ng-admin@2534ba38da30413ad62d5cae59934f696b18672a

### PR DESCRIPTION
**Pull request by vasiakorobkin**
Fixes #535

### CODE REVIEW

**Comment by jpetitcolas** [comment]
Good to me. Can you just add a test to prove the bug fix? :)

**Comment by fzaninotto** [comment]
No idea why the protractor build failed, I just restarted it.

**Comment by vasiakorobkin** [comment]
Wrote end-to-end test to prove the bug fix.

**Comment by jpetitcolas** [comment]
Needs rebase

**Comment by jpetitcolas** [comment]
Can you prefix all your PR ready for review or merge by `[RFR]`? Would be easier to priorize our reviews. :)

**Comment by fzaninotto** [comment]
still needs rebase...

**Comment by vasiakorobkin** [comment]
Rebased branch and `git push -f`'ed it to `vasiakorobkin/ng-admin`.

**Comment by jpetitcolas** [comment]
A last rebase to get a green tick from Travis? :)

**Comment by vasiakorobkin** [comment]
Rebased. All test has been passed successfully.

**Comment by jpetitcolas** [comment]
I merged another of your PR. Can you rebase a last time? :)

**Comment by vasiakorobkin** [comment]
Done.

**Comment by jpetitcolas** [comment]
Superseeded by #642.

**Pull request closed without merging**
