### PR TITLE
[RFR] Fix DateField watches

### LINKED ISSUE #1271: editionView() returns date decremented by 1 day
### Description

In my index.js:
```
project.editionView().fields([
         nga.field('devdate', 'date')
           .format('MM-dd-yyyy')
           .label('Development Date'),
    ]);
```
The day (dd) is decremented by 1 but the above works fine (displays the correct `devdate` response) in `project.creationView().fields`. 

### Steps to Reproduce
Plunkr: http://plnkr.co/edit/M70PbzPLBCGVZ9dollvj?p=preview

0. Set the browser to CST or any timezone less than GMT
1. Select 'Projects' in the left hand pane
2. Select 'Id' of any of the projects in the Project List; notice the 'Dev Date'
3. Now in the Edit Project form, the 'Development Date' displays decremented by 1 day
4. If user chooses to save, the 'Dev Date' will be stored in the db incorrectly.

I've tried it with and without the `.format` and `.label` with the same results. Again, creationView works just fine. And the datepicker requests with the `devdate:"2016-12-08"` so it is stored in the database accurately.

**Expected behavior:** Display 12-07-2016

**Actual behavior:** Displays 12-06-2016

### LINKED ISSUE #1305: Date field cannot be typed in
If you have a 'date' field, you can no longer type the date in it explicitly. Attempting to modify an existing date also just deletes it.

You can see the behaviour in the ng-admin demo - https://marmelab.com/ng-admin-demo/index.html#/customers/edit/485 - try changing the birthday without opening the picker.

I think this was broken by https://github.com/marmelab/ng-admin/issues/899 - it used to work in an older version of ng-admin.

The problem is because maDateField watches both value and rawValue:

```
            scope.$watch('rawValue', function(newValue) {
                scope.value = field.parse()(newValue);
            });

            scope.$watch('value', (newValue, oldValue) => {
                if (newValue === oldValue) {
                    return;
                }

                if (!newValue) {
                    scope.rawValue = null;
                    return;
                }

                scope.rawValue = scope.value instanceof Date ? scope.value : new Date(scope.value);
            });
```

The problem is, if at any point an invalid date string is in the box - suppose the string 'foo'. The following sequence happens:
- `$watch('rawValue'` sees `foo`. This is not a date object, so `parse` leaves it unchanged, and `value` is set to `foo`.
- `$watch('value'` sees `foo` and attempts to construct a new Date object using it. This ends up setting `rawValue` to an `Invalid Date` object.
- `$watch('rawValue'` sees `Invalid Date`. This is a date object, so `parse` tries to manipulate it, but fails and ends up setting the value to `null`. 
- `$watch('value'` sees `null` and correspondingly sets `rawValue` to `null`
- `$watch('rawValue'` sees `null` and correspondingly sets `value` to `null`
- `$watch('value'` sees `null`, this is the same as the last value, and the cycle ends!

The net result is `null` - which removes the text you tried to write from the box.

----

This is related to https://github.com/marmelab/ng-admin/issues/1271 which will be caused by a similar loop. However in that case, if you are in a timezone, the value/rawValue watches will loop, and because the 'parse' method applies a timezone correction the value never stabilises (resulting in the infinite loop).

### PR DESCRIPTION
**Pull request by Kmaschta**
Related to #1271
Fix #1305
Supersede #1317

### CODE REVIEW

**Comment by matheo** [comment]
The persisting but minor issue is that the date selector also modify the original value I guess, because when you select a date it works fine, but if you open again, it show the previous date as selected. Maybe that plugin is having the timezone difference too.
This date-time stuff is quite sensible, Javascript itself needed more clarity handling these values.

**Comment by Kmaschta** [comment]
I agree.
To be sure to sully understand you, can you open/complate an issue about that, with a simple example to reproduce it ?
Thanks

**Comment by matheo** [comment]
I'm short of time right now,
and I guess that timezone issues will arise everywhere due to the multiple String <-> Date conversion on javascript. First on the DateField plugin, then later in the DatePicker. I'm experiencing issues with a Date filter too. So, this timezone stuff is all around.

**Comment by thanhbuiea** [comment]
hi @Kmaschta , we still have problem with `Infinite Loop` due to `DateField watches`. I'm now on the latest version. This fix seems not to be able to resolve the bug. Could you please double check on it? If you need any clue or log, please let me know. Thanks. Hope to see you reply on this soon.

**Pull request merged**
